name: dating_app
description: A Dating App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  coolicons: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.2.1
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^15.1.1
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.2
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.0
  go_router: ^9.0.3
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.5.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.4.0
  permission_handler: ^11.0.1
  pinput: ^2.2.31
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/icons/splash.png
  image_dark: assets/icons/splash.png

  fullscreen: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
